import Head from "next/head"
import {Fragment, ReactElement} from "react"
import {InnerLayout, Layout} from "~components/layout"
import Image from "next/image"

import Title from "~components/title"
import type {GetStaticProps} from "next/types"
import {getAllCardImages} from "~lib/graph-cms"

type Card = {
  name: string
  image: string
  cardSlug: string
  price: number
}

type CardProps = {
  card: Card
}
const Card = ({card}: CardProps) => {
  const {name, image, cardSlug, price} = card
  return (
    <div className="min-w-[6rem] min-h-[6rem] ">
      <div className="border-2 border-slate-500 rounded-md shadow-md relative group mix-blend-multiply bg-blue-400">
        <div className="rounded-md relative">
          <Image
            src={`/images/${image}.jpeg`}
            alt="Picture of the author"
            width={500}
            height={440}
            priority
          />
        </div>
        <div className="overlay absolute top-0 left-0 bg-slate-800 w-full h-full opacity-40"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 md:text-xl text-white hidden group-hover:flex group-hover:flex-column transition-all ease-in-out">
          <p>{name}</p>
          <p>{price}$</p>
          <button>add {name} to cart</button>
        </div>
      </div>
    </div>
  )
}

interface Props {
  cards: Card[]
}
const Home = ({cards}: Props): JSX.Element => {
  return (
    <Fragment>
      <Title>
        <h1>Masiu&apos;s Sick images</h1>
      </Title>
      <p>Top 6 images of the week</p>
      <div className="grid grid-cols-1 sm:grid-cols-2  md:grid-cols-3 gap-2 p-2">
        {cards.map(card => (
          <Card key={card.cardSlug} card={card} />
        ))}
      </div>
    </Fragment>
  )
}

Home.getLayout = function (page: ReactElement) {
  return (
    <Fragment>
      <Head>
        <title>E commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InnerLayout>{page}</InnerLayout>
      </Layout>
    </Fragment>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const cards = await getAllCardImages()
  return {
    props: {
      cards,
    },
  }
}

export default Home
