import Head from "next/head"
import {Fragment, ReactElement} from "react"
import Layout, {InnerLayout} from "~components/layout/layout"
import Image from "next/image"

const Card = ({name}: {name: string}) => (
  <div className="min-w-[6rem] min-h-[6rem]">
    <div>
      <div className="rounded-md">
        <Image
          src={`/images/${name}.jpeg`}
          alt="Picture of the author"
          width={500}
          height={500}
          priority
        />
      </div>
      <p>{name}</p>
    </div>
    <button>add {name} to cart</button>
  </div>
)

const cards = [
  {name: "card-1"},
  {name: "card-2"},
  {name: "card-3"},
  {name: "card-4"},
  {name: "card-5"},
  {name: "card-6"},
]

const Home = (): JSX.Element => (
  <Fragment>
    <Head>
      <title>E commerce</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>
      <h1>Masiu&apos;s Sick images</h1>
    </div>
    <p>Top 6 images of the week</p>
    <div className="grid grid-cols-1 sm:grid-cols-2  md:grid-cols-3 gap-2">
      {cards.map(({name}) => (
        <Card name={name} key={name} />
      ))}
    </div>
  </Fragment>
)
Home.getLayout = function (page: ReactElement) {
  return (
    <Layout>
      <InnerLayout>{page}</InnerLayout>
    </Layout>
  )
}

export default Home
