import Head from "next/head"
import {Fragment, ReactElement} from "react"
import Layout, {InnerLayout} from "~components/layout/layout"
import Image from "next/image"
import cards from "~data/static-images.json"
import Title from "~components/title"

const Card = ({name}: {name: string}) => (
  <div className="min-w-[6rem] min-h-[6rem] ">
    <div className="border-2 border-slate-500 rounded-md shadow-md relative group mix-blend-multiply bg-blue-400">
      <div className="rounded-md relative">
        <Image
          src={`/images/${name}.jpeg`}
          alt="Picture of the author"
          width={500}
          height={440}
          priority
        />
      </div>
      <div className="overlay absolute top-0 left-0 bg-slate-800 w-full h-full opacity-40"></div>
      <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 md:text-2xl text-white hidden group-hover:flex transition-all ease-in-out">
        <p>{name}</p>
        <button>add {name} to cart</button>
      </div>
    </div>
  </div>
)

const Home = (): JSX.Element => (
  <Fragment>
    <Title>
      <h1>Masiu&apos;s Sick images</h1>
    </Title>
    <p>Top 6 images of the week</p>
    <div className="grid grid-cols-1 sm:grid-cols-2  md:grid-cols-3 gap-2 p-2">
      {cards.map(({name}) => (
        <Card name={name} key={name} />
      ))}
    </div>
  </Fragment>
)

Home.getLayout = function (page: ReactElement) {
  return (
    <Fragment>
      <Head>
        <title>E commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InnerLayout>{page}</InnerLayout>
      </Layout>
    </Fragment>
  )
}

export default Home
